### ISSUE TITLE
Bloop

### ISSUE THREAD

**Issue by pauldraper** [andyscott/rules_scala_annex#91]
There's some non-functioning file that've been earmarked as the point of a possible Bloop integration.

I'm personally not of an opinion that Bloop is right abstraction here as opposed in Zinc, but I'm not an expert and this is the skunkworks after all, right?

Anyway, what's the game plan? Do we need to keep Bloop stubs around, or can we clear out the clutter and put it back when something actually exists? @andyscott  @jvican

**Comment by jvican** [comment]
I would prefer to keep them around and settle on a Bloop integration. Many of the points I illustrated in https://github.com/bazelbuild/rules_scala/issues/328#issuecomment-418922044 apply here.
  
@pauldraper @jjudd What about we jump on a call to discuss this topic and also find a more reliable way for you to cover your unused dependencies use case?

**Comment by pauldraper** [comment]
> also find a more reliable way for you to cover your unused dependencies use case

I might have missed something, but I think rules_scala_annex currently has a very reliable way. (Would be interested in a contrary example, though.)

I'm fine with keeping Bloop "hooks" around for future possible development, though I don't have much interest in contributing myself to the Bloop integration.
